### ISSUE TITLE
Air nodes can be dropped and are invisible to the inventory.

### ISSUE THREAD

**Issue by t4im** [DonBatman/mysponge#2]
The Air nodes lack description and provide an invisible Inventory Image.  While neither is needed (or harmful) for mod-placed nodes, lacking these makes it unnecessary inconvenient removing them from inventories should they ever land there (for example due to another mod dropping those nodes).
Imagine not being able to dig up a seemingly empty chest.

They should not provide an invisible tile texture (the default generated unknown item image is fine), but a description, both which can help identifying any items already sitting around in chests and other inventories by accident, so that they can be removed. They also should set `drop=""` so that they don't return an ItemStack, should another mod dig them.

**Comment by DonBatman** [comment]
I made the changes but did not test. If there are any issues please let me know.
I do not mind if you do PRs. I have a lot going on in my personal life and do not have much time for minetest.

**Comment by t4im** [comment]
Seems to work. Thanks. Gonna PR next time; just assumed that you'd be active atm, and want to take care of it yourself. :-)
